### ISSUE TITLE
admin_update_profile should accept username

### ISSUE THREAD

**Issue by ba1dr** [errietta/mandate#6]
Method `admin_update_profile` does not accept username and instead updates current user. Whereas function `admin_update_user_attributes` from BOTO3 declares that it works on any user.

Without this function it is not possible to change other user's attributes as admin.

As a required action (that I met myself) this states:

> In addition to updating user attributes, this API can also be used to mark phone and email as verified.

**Comment by errietta** [comment]
Thanks for the report, will look later! As an aside, I forked `warrant` so I may be missing some features they implemented, so will look further

**Comment by errietta** [comment]
This has been fixed in 0.3.0 - https://pypi.org/project/mandate/0.3.0/
